version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Building source code...
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
