AWSTemplateFormatVersion: "2010-09-09"

Description: "lambda-ts template"

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    CodeUri: build/
    Runtime: nodejs14.x
    Timeout: 300
    Architectures:
      - x86_64

Resources:
  LambdaTs:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      FunctionName: "lambdaTs_demo"
      Handler: index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /lambdats
