AWSTemplateFormatVersion: "2010-09-09"

Description: "lambda-ts DEV template"

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    CodeUri: build/
    Runtime: nodejs14.x
    Timeout: 300

Resources:
  LambdaTsSummation:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      Handler: summation.handler
      Events:
        LambdaTs:
          Type: Api
          Properties:
            Path: /sum
            Method: GET

  LambdaTsSubtraction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      Handler: subtraction.handler
      Events:
        LambdaTs:
          Type: Api
          Properties:
            Path: /subtract
            Method: GET
